### ISSUE TITLE
No index.php

### ISSUE THREAD

**Issue by Beorn619** [Byorun/beatsaver-laravel#1]
Hi, I would love to help you with the project but I once I cloned the repo to my local machine I could not find and index.php or index.html file anywhere. Sorry if this is not the right place but I didn't know where else to contact you. I am happy to help with php or html & css if you need any.

Thanks,

-Beorn :)

**Comment by Byorun** [comment]
the index.php is in /public/[index.php](https://github.com/Byorun/beatsaver-laravel/blob/master/public/index.php). you should make yourself familiar with the [laravel ](https://github.com/Byorun/beatsaver-laravel/blob/master/laravel.md)framework.

You can also contact me in the modding discord channel.
