### ISSUE TITLE
Bug: Paged views (newest, downloads, etc) fail if crossing 100

### ISSUE THREAD

**Issue by xbkingx** [Byorun/beatsaver-laravel#17]
For Newest, Downloads, and Played URLs, there will be no "Next Page" button for ../86 to ../99.

Example:
Next button present: https://beatsaver.com/browse/newest/85
Next button missing: https://beatsaver.com/browse/newest/86
Next button present: https://beatsaver.com/browse/newest/100
Next button missing: https://beatsaver.com/browse/newest/99

The transition to 1000 works, just the transition to 100 is wonky.

Also, it's possible to add a bunch of stuff to the last element of the URL and get results instead of an error. These work:
https://beatsaver.com/browse/newest/-3
https://beatsaver.com/browse/newest/+3
https://beatsaver.com/browse/newest/3+3
https://beatsaver.com/browse/newest/abs(-3)
https://beatsaver.com/browse/newest/(3+3)
It doesn't change what's displayed (mostly) and equations aren't evaluated, but the Next Page button disappears.

**Comment by Byorun** [comment]
It its planned to replace the offset based paging with a page paging. This will hopefully fix the clunky behaviour of the whole paging

**Comment by Byorun** [comment]
The  first part should be fixed with #22 . The second one will most likely stay until the current paging is replaced do to the nature laravel parses the routes.
