### ISSUE TITLE
What happened to the viewing of songs?

### ISSUE THREAD

**Issue by WulfBreaker** [Byorun/beatsaver-laravel#22]
i used to be able to come in and look through the newest all the way too the end if I so chose. which is a lot of pages. and I honestly loved checking back every once and awhile and just checking whats there. it also introduced me to a whole bunch of songs I never knew existed. 
    now on Newest, top played ect. I can go to page 6 then there is no next page button. all I can really do is just search. which I don't even know what I want or it doesn't exist half the time. I just liked scrolling through and finding new stuff. is this a issue or was it purposeful ? because I really don't like this.

**Comment by Byorun** [comment]
That was not intentional. 
as a workaround you can use https://beatsaver.com/browse/newest/100 (you will missing 10 songs).
this is most likely a side effect from the top100 caching i did a few weeks ago

**Comment by Byorun** [comment]
the new release will "fix" this issue until a real paging is in place
