### ISSUE TITLE
Dev environment, verification link

### ISSUE THREAD

**Issue by Razzeee** [Byorun/beatsaver-laravel#25]
I'm a bit confused, and need some instructions on how to verify after I created my user. As I won't get an email with email driver set to `log`. What's the best way to do this?

**Comment by Byorun** [comment]
search in storage/log/laravel.log. The complete email will be outputted there (incl. verification code)

**Comment by Byorun** [comment]
@Razzeee do you still have problems with the verification link?

**Comment by Razzeee** [comment]
No tried it today, works as expected.
