### ISSUE TITLE
Filter @ Commands from the discord website

### ISSUE THREAD

**Issue by beatsaver** [Byorun/beatsaver-laravel#31]
pretty much its an issue, but we need to filter all @ commands out of the webhook before posting

so like

@everyone
@Admin

things like that

**Comment by Byorun** [comment]
the discord webhook has no @ in the posting text

```$message->setContent("New song uploaded by **{$songData['uploader']}** : " . route('browse.detail', ['key' => $songData['key']]));```

**Comment by JRWR** [comment]
Interesting, You are correct!
