### ISSUE TITLE
Description cannot be null

### ISSUE THREAD

**Issue by Razzeee** [Byorun/beatsaver-laravel#34]
If you upload a new song, you will have to fill out the title, but not the description.

If you then try to change the title on the created song, it will error out due to the description being null.

**Comment by Byorun** [comment]
If  you (by any chance) have a dev environment you could try adding a null to empty string convert in https://github.com/Byorun/beatsaver-laravel/blob/develop/app/Http/Controllers/BeatSaverController.php#L264 and following.

**Comment by Razzeee** [comment]
Can you let me know how the code should look, has been some time since I did php/laravel.

**Comment by Byorun** [comment]
something like ```php $variable = is_null($variable) ? '' : $variable;``` there are many ways to check(e.g. with a simple IF statement). You could also move that into the update function a few lines later.
