### ISSUE TITLE
Bug: Song parser not checking for inconsistent filenames (json vs real filename)

### ISSUE THREAD

**Issue by lolPants** [Byorun/beatsaver-laravel#7]
Some songs have been uploaded with the file `normal.json` rather than `Normal.json`  
This breaks part of andruzzzhka's multiplayer plugin.

Perhaps it would be a good idea to reject or normalise inconsistencies in the capitalisation of difficulty levels.

Examples:
https://beatsaver.com/api/songs/detail/2376-1644  
https://beatsaver.com/api/songs/detail/3301-2360

**Comment by Byorun** [comment]
We won't edit uploaded zips (as of now). So rejecting them would be the only way. But this should already be happening.

**Comment by Byorun** [comment]
After i talked to the song loader author, I decided to not restrict the upload process any further. I also forwarded the bug to "andruzzzhka's multiplayer plugin"
