### ISSUE TITLE
Public api is not working 

### ISSUE THREAD

**Issue by vladern** [Byorun/beatsaver-laravel#86]
API request is not working:
![image](https://user-images.githubusercontent.com/17649603/59871265-6c6df100-9397-11e9-9773-7b2168ff3a9b.png)

**Comment by Assistant** [comment]
The codebase here isn't in use anymore, so naturally endpoints in it won't necessarily work.
[Here is the currently deployed codebase.](https://github.com/beat-saber-modding-group/beatsaver-reloaded)
